use_default_settings: true

general:
  instance_name: "ComFind Search"

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

server:
  secret_key: "ComFind-SearXNG-67f3mb8xx0vy7IN5"
  bind_address: "0.0.0.0"
  port: 8080
  base_url: false
  image_proxy: false

ui:
  static_use_hash: true

engines:
  - name: google
    engine: google
    shortcut: go

  - name: bing
    engine: bing
    shortcut: bi

  - name: brave
    engine: brave
    shortcut: br
